name = "bookingapp-telegram"
main = "src/worker.js"
compatibility_date = "2026-09-02"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "booking-app-db"
database_id = "b6685e53-b6f1-4f6f-8869-226c295d8ef1"

[triggers]
crons = ["0 10 * * *"]
